/*
 ================================================================================================
 Module		 : ULTRASONIC

 Name        : ultrasonic.c

 Author      : Hassan Sabry Ahmed Shahin

 Description : source file for ULTRASONIC

 Date        : Apr 20, 2023
 ================================================================================================
 */



#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h>

/*global variable to count num of edges*/
uint8 g_edgeCount = 0;

/*global variable to count high time of trigger*/
uint16 g_timeHigh = 0;

/*global variable to count ultrasonic distance*/
 uint16 g_distance = 0;




/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){


	g_edgeCount++;

	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}
}

/*
 * Description:
 * Initialize the ultrasonic drive by:
 *Initialize the ICU driver as required.
 *Initialize  Setup the ICU call back function.
 *Initialize the trigger pin direction.
 */


/*
 * Description:
 * Send the Trigger pulse to the ultrasonic.
 */

void Ultrasonic_Trigger(void){


	/*SETUP TRIGGER PIN AS OUTPUT PIN*/
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_HIGH);

	/*Time to transmit trigger pulse*/
	_delay_us(10);

	/*SETUP TRIGGER PIN AS INPUT PIN*/
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_LOW);

}

void Ultrasonic_init(void){

	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};

	/*SETUP TRIGGER PIN AS OUTPUT PIN*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,PIN_OUTPUT);

	/* Function to initialize the ICU driver*/
	Icu_init(&Icu_Config);

	/*Function to set the Call Back function address*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);


}


/*
 * Description:
 *Send the trigger pulse by using Ultrasonic_Trigger function.
 *Send Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){


	/* Clear all variables as they may have values from previous read operation */
	g_distance = 0;
	g_edgeCount = 0;
	g_timeHigh = 0;

	/* Clear the timer counter register to start measurements once trigger is sent */
	Icu_clearTimerValue();

	/* Send the trigger to activate the Ultra-sonic sensor (Start measurements) */
	Ultrasonic_Trigger();

	/* Wait until the ICU measures the pulse in the ECHO pin */
	while(g_edgeCount != ULTRASONIC_NUM_OF_EDGES);

	/* Calculate the distance in Centimeter value */
	g_distance = g_timeHigh / 58;

	return g_distance;
}





